type Book {
  title: String
  author: Author
}

type Author {
  name: String
  books: [Book]
}

type Query {
  books: [Book]
  authors: [Author]
  greet(names: [String!]!): [String]
  greetDotNet(names: [String!]!): [String]
  getAge(name: String!): Int
  calculate(a: Float!, b: Float!, operation: String!): CalculatorResult
}

type CalculatorResult {
  result: Float
  operation: String
  expression: String
}

type Mutation {
  addBook(title: String, author: String): Book
}